### ISSUE TITLE
Hello,the space between snake body is too big

### ISSUE THREAD

**Issue by jjjjilyf** [XavierLeTohic/snake-vs-block#1]
Is ther any way to let them keep tight to move left no void pix?thx.

**Comment by XavierLeTohic** [comment]
Hi there,

I just pushed an update, increasing the snake tail speed but I'm not able to get the same behaviour such as the native "snake vs block" on IOS/Android.

The code related to the tail is located on src/play.js and the method name is ```updateCircles``` (I agree the semantic is not good)

**Comment by jjjjilyf** [comment]
Thanks so much.But I have solved the issue by record every pixel the snake moves and move by pixel.So it can play like the native "snake vs block".
